### ISSUE TITLE
What do you do with models to make them work?

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [armory3d/armorai#2]
Greetings.
https://github.com/armory3d/armorlab/blob/a3fbea595478637de59efac7f7f38c746e57a08f/Sources/arm/node/brush/PhotoToPBRNode.hx#L63-L76
Why is this needed? Is this an "obfuscation"? Please, tell me.
I wanted to use your models in complex [chaiNNer](https://github.com/joeyballentine/chaiNNer) nodes, but it seems impossible because of this.

https://github.com/joeyballentine/chaiNNer/issues/808

**Comment by luboslenco** [comment]
Hi, the model is run at 2176x2176 resolution, then the borders are cut to form a 2048x2048 texture.

**Comment by 0x4E69676874466F78** [comment]
@luboslenco I understand that, but what happens to the colors there?

**Comment by 0x4E69676874466F78** [comment]
You first do [something with colors](https://github.com/armory3d/armorlab/blob/a3fbea595478637de59efac7f7f38c746e57a08f/Sources/arm/node/brush/PhotoToPBRNode.hx#L58-L60), then send it to the model and then [return the colors back](https://github.com/armory3d/armorlab/blob/a3fbea595478637de59efac7f7f38c746e57a08f/Sources/arm/node/brush/PhotoToPBRNode.hx#L72-L74).

**Comment by 0x4E69676874466F78** [comment]
![изображение](https://user-images.githubusercontent.com/4449851/186407043-6fb6d12e-0f97-48b9-8ed9-07e39aeefa3e.png)

**Comment by 0x4E69676874466F78** [comment]
Is this a translation into linear space?

**Comment by 0x4E69676874466F78** [comment]
Yes. I got it.
